### ISSUE TITLE
Component breaks Home Assistant history

### ISSUE THREAD

**Issue by plantoschka** [panbachi/homeassistant-tankerkoenig#1]
I've installed and configured this component and everything was looking fine. Today I noticed that all my history graphs don't show any changes since yesterday.

In the Home Assistant Log I see this error in record/util.py:
`Error executing query: Object of type 'timedelta' is not JSON serializable`

After removing tankerkoenig: from my configuration.yaml everything works fine.

**Comment by napsio** [comment]
Thanks for this information. I fixed the component and the history must work now again like expected when you update the component.
