### ISSUE TITLE
tankerkoenig broken with HA 88.0

### ISSUE THREAD

**Issue by magenbrot** [panbachi/homeassistant-tankerkoenig#2]
Hi,
starting with 87.0 homeassistant made some changed in the custom_components file structure. Please have a look: https://developers.home-assistant.io/blog/2019/02/19/the-great-migration.html

tankerkoenig is currently not working for me.

Best regards
Oli

**Comment by napsio** [comment]
Hi,

I've updated the repository, so can you try if it is working now?

Best regards

**Comment by magenbrot** [comment]
Hi! 

thanks, it works fine! I've also made a PR for a related suggestion from the HA devs. Please have a look on #3

Best regards
Oli
